### ISSUE TITLE
Eventual crash even though job completed successfully

### ISSUE THREAD

**Issue by daku** [billmalarky/react-native-queue#2]
Sorry I have not investigated a lot yet, but it looks like the timeout logic for successful jobs maybe getting executed. Since the job is no longer there, the crash happens. Again just a guess by briefly looking at `Worker.js` and `Queue.js` and because the crash does not happen immediately. I usually have to wait around the timeout time for it to happen.

![screen shot 2018-01-21 at 1 15 02 pm](https://user-images.githubusercontent.com/107758/35199079-96c5405a-fead-11e7-8f76-551ab533f8ec.png)

**Comment by billmalarky** [comment]
Thank you, I will investigate this further!

**Comment by billmalarky** [comment]
I am out of office until Monday when I can tackle it next. Can you copy
paste any errors you receive? Especially with the line of code the error is
thrown on?

**Comment by billmalarky** [comment]
I'm struggling to recreate this. @Cumquat which advanced example did you see it on?

@daku , could it be some bad jobs were created during your development and you need to flush the queue in order to start with a clean slate once your development wraps up?

try

`
queue.flushQueue();
// Then check that all the jobs have been deleted like so
const jobs = await queue.getJobs(true);
console.log(jobs.length, 'Jobs currently in queue');
`

After flushing the queue, are you seeing the error thrown again?

**Comment by daku** [comment]
@billmalarky thank you for looking into it. I can reproduce this after a full uninstall/install of the app on both platforms (ios and android). The db should be empty at that point, I am guessing. I will try to do what you said and see what happens though.

My perspective on the solution was that when the job is deleted, any pending timeouts need to be cancelled as well. I believe that isn't happening now. To reproduce, the timeout would have to be longer than the expected length of the job.

**Comment by billmalarky** [comment]
@daku You were correct.

The bug exists in the job timeout logic found in [Worker.executeJob()](https://github.com/billmalarky/react-native-queue/blob/master/Models/Worker.js#L85-L109).

The timeout promise code always executes (as expected), this planned behavior is generally benign because Worker.executeJob() returns Promise.race() which returns the first promise in the race to resolve or reject (the other promises complete more or less "into the ether" as far as the library logic is concerned<sup>1</sup>). From my research, this is the best practice way to build timeout logic in js. Unfortunately there's no way to cancel the execution of the laggard promises in the race when the first promise completes that's just the nature of the beast with js.

Anyways, the bug appears [here](https://github.com/billmalarky/react-native-queue/blob/master/Models/Worker.js#L98-L99) when we try to access job data after the job has already been destroyed because the worker promise resolved faster than the timeout promise rejected (ie the job didn't time out). One of the quirks of realm is that realm objects are never stale, so even just accessing properties on the job realm object will ping realm for the latest data - data that of course no longer exists since we deleted the job when it completed successfully prior to the timeout code running.

I've scheduled time to patch this tomorrow. Thank you for bringing it to my attention.

Footnotes:  
[1] This javascript limitation is another reason why [jobs must be idempotent](https://github.com/billmalarky/react-native-queue#caveats).

**Comment by daku** [comment]
@billmalarky thank you for the explanation! Your solution sounds great, as long as job data is not accessed if the job does not exist then we most likely will not see this error.

**Comment by billmalarky** [comment]
Ok this is patched, thank you for your help guys!

https://github.com/billmalarky/react-native-queue/pull/5

**Comment by daku** [comment]
Thank you! I'll test it out as soon as I can.

On Jan 31, 2018 1:28 PM, "Reid Mayo" <notifications@github.com> wrote:

Ok this is patched, thank you for your help guys!

#5 <https://github.com/billmalarky/react-native-queue/pull/5>

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/billmalarky/react-native-queue/issues/2#issuecomment-362076520>,
or mute the thread
