### ISSUE TITLE
[Question] Would it be possible to make it work with joltup/react-native-threads

### ISSUE THREAD

**Issue by tmoubarak** [billmalarky/react-native-queue#21]
Hi Bill,

I think what you have done here is really useful!  

I want to ask you if it is possible to use  react-native-threads: https://github.com/joltup/react-native-threads for background processing since it seems to be better maintained than the workers.

Please let me know if it is possible... In parallel I will be trying to set it up as well.
Thank you in advance!,
Tarek M.

**Comment by billmalarky** [comment]
Hello Tarek,

Almost certainly. React Native Queue is designed to be agnostic and able to integrate with basically anything. It's a standalone task management solution. In fact, it actually doesn't even have any dependencies on React Native even, you could use this queue in any js environment Realm will work in. That said I built it specifically because there was a need for something like this in React Native apps thus the name.

After looking at react-native-threads, the integration solution will basically be the same as react-native-workers.

See an example integration here: https://gist.github.com/billmalarky/1d1f72a267a1608606410602aa63cabf

**Comment by tmoubarak** [comment]
Thank you very much for your swift reply!!

**Comment by billmalarky** [comment]
For sure! Hope it helped.

**Comment by tastyqbit** [comment]
Hi! I can't seem to get this working. In the example, all the thread code is in the same file. Is that what the instruction is and if so where does the path to the worker point?

It seems as though react-native-threads is not working with realm as realm doesn't support multiprocess applications. I confirmed this by installing the react-native-threads example, confirmed it worked and then installed realm which then broke the example. 

Any advice? Help would be really appreciated!
