### ISSUE TITLE
what's the meaning of timeout of job?

### ISSUE THREAD

**Issue by fatfatson** [billmalarky/react-native-queue#23]
for the example in the `Basic Usage` in homepage,
timeout job is still executing,
so what's meaning of timeout?

**Comment by fatfatson** [comment]
and i don't know when  a job will be considered `Fail`? since there's no method for marking a job is success or fail...
if a fail is only due to the timeout, then what's the meaning of attempts? all the retry will still fail.

**Comment by billmalarky** [comment]
The purpose of job timeouts are to make sure a job doesn't hang unexpectedly and block the queue. 

Yes the "abondoned" long running job handler will continue to run in the background until it is completed or killed naturally (this is a limitation of JavaScript that can't be overcome currently) even after a job has been marked as failed due to timeout, but that is an acceptable outcome so long as your jobs are designed to be idempotent as they must be.

Also, timing out a job sets a definable moment in time a job in the queue can be objectively marked as failed even if the handler continues processing. This is especially important for example if you are using react native queue in a background task as those are often limited by the phones OS to a max execution time of 30 seconds. Thus we need to enforce that a job has either completed successfully or is forced to be marked as "failed" due to time out in the queue persistence layer before hitting the OS hard limit of 30 seconds.

Does this help explain? I can clarify further if you need.

**Comment by billmalarky** [comment]
>if a fail is only due to the timeout, then what's the meaning of attempts? all the retry will still fail.

Not necessarily, there are plenty of situations where a job would take longer than usual to complete so just because it times out one time doesn't mean it won't succeed next time.

The first thing that comes to mind is network congestion. Sometimes a http request will hang and the next time it will resolve instantly. That's just the nature of the internet.

**Comment by fatfatson** [comment]
thanks @billmalarky
I have misunderstood the timeout prop is the time how long the task should wait for starting.
